import respx
import httpx

from mds.agg_mds.adapters import get_metadata


@respx.mock
def test_get_metadata_icdc():
    json_response = r"""{
   "data":{
      "studiesByProgram":[
         {
            "program_id":"COP",
            "clinical_study_designation":"COTC007B",
            "clinical_study_name":"Preclinical Comparison of Three Indenoisoquinoline Candidates in Tumor-Bearing Dogs",
            "clinical_study_type":"Clinical Trial",
            "numberOfCases":84,
            "numberOfCaseFiles":0,
            "numberOfStudyFiles":0,
            "numberOfImageCollections":0,
            "numberOfPublications":2,
            "accession_id":"000001",
            "study_disposition":"Unrestricted",
            "numberOfCRDCNodes":0,
            "CRDCLinks":[

            ],
            "__typename":"StudyOfProgram"
         },
         {
            "program_id":"COP",
            "clinical_study_designation":"COTC022",
            "clinical_study_name":"A Contemporaneous Controlled Study of the Standard of Care (SOC) in Dogs with Appendicular Osteosarcoma",
            "clinical_study_type":"Clinical Trial",
            "numberOfCases":157,
            "numberOfCaseFiles":0,
            "numberOfStudyFiles":2,
            "numberOfImageCollections":0,
            "numberOfPublications":1,
            "accession_id":"000009",
            "study_disposition":"Unrestricted",
            "numberOfCRDCNodes":0,
            "CRDCLinks":[

            ],
            "__typename":"StudyOfProgram"
         },
         {
            "program_id":"CMCP",
            "clinical_study_designation":"GLIOMA01",
            "clinical_study_name":"Comparative Molecular Life History of Spontaneous Canine and Human Gliomas",
            "clinical_study_type":"Genomics",
            "numberOfCases":81,
            "numberOfCaseFiles":858,
            "numberOfStudyFiles":0,
            "numberOfImageCollections":2,
            "numberOfPublications":1,
            "accession_id":"000003",
            "study_disposition":"Unrestricted",
            "numberOfCRDCNodes":2,
            "CRDCLinks":[
               {
                  "text":"ICDC-Glioma01 - TCIA",
                  "url":"https://doi.org/10.7937/TCIA.SVQT-Q016",
                  "__typename":"Link"
               },
               {
                  "text":"ICDC-Glioma (GLIOMA01) - IDC",
                  "url":"https://imaging.datacommons.cancer.gov/explore/?filters_for_load\u003d[{\"filters\":[{\"id\":\"120\",\"values\":[\"icdc_glioma\"]}]}]",
                  "__typename":"Link"
               }
            ],
            "__typename":"StudyOfProgram"
         },
         {
            "program_id":"CMCP",
            "clinical_study_designation":"MGT01",
            "clinical_study_name":"Molecular Homology and Differences Between Spontaneous Canine Mammary Cancer and Human Breast Cancer",
            "clinical_study_type":"Genomics",
            "numberOfCases":13,
            "numberOfCaseFiles":68,
            "numberOfStudyFiles":0,
            "numberOfImageCollections":0,
            "numberOfPublications":2,
            "accession_id":"000007",
            "study_disposition":"Unrestricted",
            "numberOfCRDCNodes":0,
            "CRDCLinks":[

            ],
            "__typename":"StudyOfProgram"
         },
         {
            "program_id":"COP",
            "clinical_study_designation":"NCATS-COP01",
            "clinical_study_name":"Models for Diagnosis and Treatment of Human Cancers Using Comparative Canine-Human Transcriptomics",
            "clinical_study_type":"Transcriptomics",
            "numberOfCases":60,
            "numberOfCaseFiles":211,
            "numberOfStudyFiles":1,
            "numberOfImageCollections":0,
            "numberOfPublications":1,
            "accession_id":"000002",
            "study_disposition":"Unrestricted",
            "numberOfCRDCNodes":0,
            "CRDCLinks":[

            ],
            "__typename":"StudyOfProgram"
         },
         {
            "program_id":"CMCP",
            "clinical_study_designation":"OSA01",
            "clinical_study_name":"A Multi-Platform Sequencing Analysis of Canine Appendicular Osteosarcoma.",
            "clinical_study_type":"Genomics",
            "numberOfCases":60,
            "numberOfCaseFiles":278,
            "numberOfStudyFiles":0,
            "numberOfImageCollections":0,
            "numberOfPublications":1,
            "accession_id":"000006",
            "study_disposition":"Unrestricted",
            "numberOfCRDCNodes":0,
            "CRDCLinks":[

            ],
            "__typename":"StudyOfProgram"
         },
         {
            "program_id":"CMCP",
            "clinical_study_designation":"TCL01",
            "clinical_study_name":"Whole exome sequencing analysis of canine cancer cell lines",
            "clinical_study_type":"Genomics",
            "numberOfCases":0,
            "numberOfCaseFiles":0,
            "numberOfStudyFiles":0,
            "numberOfImageCollections":0,
            "numberOfPublications":1,
            "accession_id":"000008",
            "study_disposition":"Pending",
            "numberOfCRDCNodes":0,
            "CRDCLinks":[

            ],
            "__typename":"StudyOfProgram"
         },
         {
            "program_id":"PCCR",
            "clinical_study_designation":"UBC01",
            "clinical_study_name":"Antitumor Activity and Molecular Effects of Vemurafenib in Dogs with BRAF-mutant Bladder Cancer",
            "clinical_study_type":"Clinical Trial",
            "numberOfCases":38,
            "numberOfCaseFiles":166,
            "numberOfStudyFiles":4,
            "numberOfImageCollections":0,
            "numberOfPublications":1,
            "accession_id":"000004",
            "study_disposition":"Unrestricted",
            "numberOfCRDCNodes":0,
            "CRDCLinks":[

            ],
            "__typename":"StudyOfProgram"
         },
         {
            "program_id":"PCCR",
            "clinical_study_designation":"UBC02",
            "clinical_study_name":"Basal and Luminal Molecular Subtypes in Naturally-Occurring Canine Urothelial Carcinoma Are Associated With Tumor Immune Signatures and Dog Breed",
            "clinical_study_type":"Genomics",
            "numberOfCases":60,
            "numberOfCaseFiles":120,
            "numberOfStudyFiles":2,
            "numberOfImageCollections":0,
            "numberOfPublications":1,
            "accession_id":"000005",
            "study_disposition":"Unrestricted",
            "numberOfCRDCNodes":0,
            "CRDCLinks":[

            ],
            "__typename":"StudyOfProgram"
         }
      ]
   }
}"""
    field_mappings = {
        "tags": [],
        "authz": "",
        "sites": "",
        "study_description_summary": "path:BriefSummary",
        "location": "",
        "subjects": "path:EnrollmentCount",
        "__manifest": "",
        "study_name_title": "",
        "study_type": "",
        "study_url": {"path": "NCTId", "filters": ["add_clinical_trials_source_url"]},
        "institutions": "path:LeadSponsorName",
        "year_awarded": "",
        "investigators_name": "path:OverallOfficial[0].OverallOfficialName",
        "protocol_name": "",
        "study_summary": "",
        "_file_manifest": "",
        "dataset_1_type": "",
        "dataset_2_type": "",
        "dataset_3_type": "",
        "dataset_4_type": "",
        "dataset_5_type": "",
        "project_number": "path:OrgStudyId",
        "dataset_1_title": "",
        "dataset_2_title": "",
        "dataset_3_title": "",
        "dataset_4_title": "",
        "dataset_5_title": "",
        "administering_ic": "",
        "advSearchFilters": [],
        "dataset_category": "",
        "research_program": "",
        "research_question": "",
        "study_description": "",
        "clinical_trial_link": "",
        "dataset_description": "",
        "research_focus_area": "",
        "dataset_1_description": "",
        "dataset_2_description": "",
        "dataset_3_description": "",
        "dataset_4_description": "",
        "dataset_5_description": "",
    }

    field_mappings = {
        "tags": [],
        "authz": "/programs/open",
        "sites": "",
        "summary": "",
        "study_description_summary": "",
        "study_url": "",
        "location": "",
        "subjects": "path:numberOfCases",
        "__manifest": "",
        "study_name": "",
        "study_name_title": "",
        "study_type": "",
        "institutions": "",
        "year_awarded": "",
        "investigators": "",
        "investigators_name": "",
        "project_title": "path:clinical_study_name",
        "protocol_name": "",
        "study_summary": "",
        "_file_manifest": "",
        "dataset_1_type": "",
        "dataset_2_type": "",
        "dataset_3_type": "",
        "dataset_4_type": "",
        "dataset_5_type": "",
        "project_number": "path:clinical_study_designation",
        "dataset_1_title": "",
        "dataset_2_title": "",
        "dataset_3_title": "",
        "dataset_4_title": "",
        "dataset_5_title": "",
        "administering_ic": "",
        "advSearchFilters": [],
        "dataset_category": "",
        "research_program": "",
        "research_question": "",
        "study_description": "",
        "clinical_trial_link": "",
        "dataset_description": "",
        "research_focus_area": "",
        "dataset_1_description": "",
        "dataset_2_description": "",
        "dataset_3_description": "",
        "dataset_4_description": "",
        "dataset_5_description": "",
        "data_availability": "available",
    }

    respx.post("http://test/ok").mock(
        return_value=httpx.Response(status_code=200, content=json_response)
    )

    assert get_metadata(
        "icdc", "http://test/ok", filters=None, mappings=field_mappings
    ) == {
        "COTC007B": {
            "_guid_type": "discovery_metadata",
            "gen3_discovery": {
                "tags": [],
                "authz": "/programs/open",
                "sites": "",
                "summary": "",
                "study_description_summary": "",
                "study_url": "",
                "location": "",
                "subjects": 84,
                "__manifest": "",
                "study_name": "",
                "study_name_title": "",
                "study_type": "",
                "institutions": "",
                "year_awarded": "",
                "investigators": "",
                "investigators_name": "",
                "project_title": "Preclinical Comparison of Three Indenoisoquinoline Candidates in Tumor-Bearing Dogs",
                "protocol_name": "",
                "study_summary": "",
                "_file_manifest": "",
                "dataset_1_type": "",
                "dataset_2_type": "",
                "dataset_3_type": "",
                "dataset_4_type": "",
                "dataset_5_type": "",
                "project_number": "COTC007B",
                "dataset_1_title": "",
                "dataset_2_title": "",
                "dataset_3_title": "",
                "dataset_4_title": "",
                "dataset_5_title": "",
                "administering_ic": "",
                "advSearchFilters": [],
                "dataset_category": "",
                "research_program": "",
                "research_question": "",
                "study_description": "",
                "clinical_trial_link": "",
                "dataset_description": "",
                "research_focus_area": "",
                "dataset_1_description": "",
                "dataset_2_description": "",
                "dataset_3_description": "",
                "dataset_4_description": "",
                "dataset_5_description": "",
                "data_availability": "available",
            },
        },
        "COTC022": {
            "_guid_type": "discovery_metadata",
            "gen3_discovery": {
                "tags": [],
                "authz": "/programs/open",
                "sites": "",
                "summary": "",
                "study_description_summary": "",
                "study_url": "",
                "location": "",
                "subjects": 157,
                "__manifest": "",
                "study_name": "",
                "study_name_title": "",
                "study_type": "",
                "institutions": "",
                "year_awarded": "",
                "investigators": "",
                "investigators_name": "",
                "project_title": "A Contemporaneous Controlled Study of the Standard of Care (SOC) in Dogs with Appendicular Osteosarcoma",
                "protocol_name": "",
                "study_summary": "",
                "_file_manifest": "",
                "dataset_1_type": "",
                "dataset_2_type": "",
                "dataset_3_type": "",
                "dataset_4_type": "",
                "dataset_5_type": "",
                "project_number": "COTC022",
                "dataset_1_title": "",
                "dataset_2_title": "",
                "dataset_3_title": "",
                "dataset_4_title": "",
                "dataset_5_title": "",
                "administering_ic": "",
                "advSearchFilters": [],
                "dataset_category": "",
                "research_program": "",
                "research_question": "",
                "study_description": "",
                "clinical_trial_link": "",
                "dataset_description": "",
                "research_focus_area": "",
                "dataset_1_description": "",
                "dataset_2_description": "",
                "dataset_3_description": "",
                "dataset_4_description": "",
                "dataset_5_description": "",
                "data_availability": "available",
            },
        },
        "GLIOMA01": {
            "_guid_type": "discovery_metadata",
            "gen3_discovery": {
                "tags": [],
                "authz": "/programs/open",
                "sites": "",
                "summary": "",
                "study_description_summary": "",
                "study_url": "",
                "location": "",
                "subjects": 81,
                "__manifest": "",
                "study_name": "",
                "study_name_title": "",
                "study_type": "",
                "institutions": "",
                "year_awarded": "",
                "investigators": "",
                "investigators_name": "",
                "project_title": "Comparative Molecular Life History of Spontaneous Canine and Human Gliomas",
                "protocol_name": "",
                "study_summary": "",
                "_file_manifest": "",
                "dataset_1_type": "",
                "dataset_2_type": "",
                "dataset_3_type": "",
                "dataset_4_type": "",
                "dataset_5_type": "",
                "project_number": "GLIOMA01",
                "dataset_1_title": "",
                "dataset_2_title": "",
                "dataset_3_title": "",
                "dataset_4_title": "",
                "dataset_5_title": "",
                "administering_ic": "",
                "advSearchFilters": [],
                "dataset_category": "",
                "research_program": "",
                "research_question": "",
                "study_description": "",
                "clinical_trial_link": "",
                "dataset_description": "",
                "research_focus_area": "",
                "dataset_1_description": "",
                "dataset_2_description": "",
                "dataset_3_description": "",
                "dataset_4_description": "",
                "dataset_5_description": "",
                "data_availability": "available",
            },
        },
        "MGT01": {
            "_guid_type": "discovery_metadata",
            "gen3_discovery": {
                "tags": [],
                "authz": "/programs/open",
                "sites": "",
                "summary": "",
                "study_description_summary": "",
                "study_url": "",
                "location": "",
                "subjects": 13,
                "__manifest": "",
                "study_name": "",
                "study_name_title": "",
                "study_type": "",
                "institutions": "",
                "year_awarded": "",
                "investigators": "",
                "investigators_name": "",
                "project_title": "Molecular Homology and Differences Between Spontaneous Canine Mammary Cancer and Human Breast Cancer",
                "protocol_name": "",
                "study_summary": "",
                "_file_manifest": "",
                "dataset_1_type": "",
                "dataset_2_type": "",
                "dataset_3_type": "",
                "dataset_4_type": "",
                "dataset_5_type": "",
                "project_number": "MGT01",
                "dataset_1_title": "",
                "dataset_2_title": "",
                "dataset_3_title": "",
                "dataset_4_title": "",
                "dataset_5_title": "",
                "administering_ic": "",
                "advSearchFilters": [],
                "dataset_category": "",
                "research_program": "",
                "research_question": "",
                "study_description": "",
                "clinical_trial_link": "",
                "dataset_description": "",
                "research_focus_area": "",
                "dataset_1_description": "",
                "dataset_2_description": "",
                "dataset_3_description": "",
                "dataset_4_description": "",
                "dataset_5_description": "",
                "data_availability": "available",
            },
        },
        "NCATS-COP01": {
            "_guid_type": "discovery_metadata",
            "gen3_discovery": {
                "tags": [],
                "authz": "/programs/open",
                "sites": "",
                "summary": "",
                "study_description_summary": "",
                "study_url": "",
                "location": "",
                "subjects": 60,
                "__manifest": "",
                "study_name": "",
                "study_name_title": "",
                "study_type": "",
                "institutions": "",
                "year_awarded": "",
                "investigators": "",
                "investigators_name": "",
                "project_title": "Models for Diagnosis and Treatment of Human Cancers Using Comparative Canine-Human Transcriptomics",
                "protocol_name": "",
                "study_summary": "",
                "_file_manifest": "",
                "dataset_1_type": "",
                "dataset_2_type": "",
                "dataset_3_type": "",
                "dataset_4_type": "",
                "dataset_5_type": "",
                "project_number": "NCATS-COP01",
                "dataset_1_title": "",
                "dataset_2_title": "",
                "dataset_3_title": "",
                "dataset_4_title": "",
                "dataset_5_title": "",
                "administering_ic": "",
                "advSearchFilters": [],
                "dataset_category": "",
                "research_program": "",
                "research_question": "",
                "study_description": "",
                "clinical_trial_link": "",
                "dataset_description": "",
                "research_focus_area": "",
                "dataset_1_description": "",
                "dataset_2_description": "",
                "dataset_3_description": "",
                "dataset_4_description": "",
                "dataset_5_description": "",
                "data_availability": "available",
            },
        },
        "OSA01": {
            "_guid_type": "discovery_metadata",
            "gen3_discovery": {
                "tags": [],
                "authz": "/programs/open",
                "sites": "",
                "summary": "",
                "study_description_summary": "",
                "study_url": "",
                "location": "",
                "subjects": 60,
                "__manifest": "",
                "study_name": "",
                "study_name_title": "",
                "study_type": "",
                "institutions": "",
                "year_awarded": "",
                "investigators": "",
                "investigators_name": "",
                "project_title": "A Multi-Platform Sequencing Analysis of Canine Appendicular Osteosarcoma.",
                "protocol_name": "",
                "study_summary": "",
                "_file_manifest": "",
                "dataset_1_type": "",
                "dataset_2_type": "",
                "dataset_3_type": "",
                "dataset_4_type": "",
                "dataset_5_type": "",
                "project_number": "OSA01",
                "dataset_1_title": "",
                "dataset_2_title": "",
                "dataset_3_title": "",
                "dataset_4_title": "",
                "dataset_5_title": "",
                "administering_ic": "",
                "advSearchFilters": [],
                "dataset_category": "",
                "research_program": "",
                "research_question": "",
                "study_description": "",
                "clinical_trial_link": "",
                "dataset_description": "",
                "research_focus_area": "",
                "dataset_1_description": "",
                "dataset_2_description": "",
                "dataset_3_description": "",
                "dataset_4_description": "",
                "dataset_5_description": "",
                "data_availability": "available",
            },
        },
        "TCL01": {
            "_guid_type": "discovery_metadata",
            "gen3_discovery": {
                "tags": [],
                "authz": "/programs/open",
                "sites": "",
                "summary": "",
                "study_description_summary": "",
                "study_url": "",
                "location": "",
                "subjects": 0,
                "__manifest": "",
                "study_name": "",
                "study_name_title": "",
                "study_type": "",
                "institutions": "",
                "year_awarded": "",
                "investigators": "",
                "investigators_name": "",
                "project_title": "Whole exome sequencing analysis of canine cancer cell lines",
                "protocol_name": "",
                "study_summary": "",
                "_file_manifest": "",
                "dataset_1_type": "",
                "dataset_2_type": "",
                "dataset_3_type": "",
                "dataset_4_type": "",
                "dataset_5_type": "",
                "project_number": "TCL01",
                "dataset_1_title": "",
                "dataset_2_title": "",
                "dataset_3_title": "",
                "dataset_4_title": "",
                "dataset_5_title": "",
                "administering_ic": "",
                "advSearchFilters": [],
                "dataset_category": "",
                "research_program": "",
                "research_question": "",
                "study_description": "",
                "clinical_trial_link": "",
                "dataset_description": "",
                "research_focus_area": "",
                "dataset_1_description": "",
                "dataset_2_description": "",
                "dataset_3_description": "",
                "dataset_4_description": "",
                "dataset_5_description": "",
                "data_availability": "available",
            },
        },
        "UBC01": {
            "_guid_type": "discovery_metadata",
            "gen3_discovery": {
                "tags": [],
                "authz": "/programs/open",
                "sites": "",
                "summary": "",
                "study_description_summary": "",
                "study_url": "",
                "location": "",
                "subjects": 38,
                "__manifest": "",
                "study_name": "",
                "study_name_title": "",
                "study_type": "",
                "institutions": "",
                "year_awarded": "",
                "investigators": "",
                "investigators_name": "",
                "project_title": "Antitumor Activity and Molecular Effects of Vemurafenib in Dogs with BRAF-mutant Bladder Cancer",
                "protocol_name": "",
                "study_summary": "",
                "_file_manifest": "",
                "dataset_1_type": "",
                "dataset_2_type": "",
                "dataset_3_type": "",
                "dataset_4_type": "",
                "dataset_5_type": "",
                "project_number": "UBC01",
                "dataset_1_title": "",
                "dataset_2_title": "",
                "dataset_3_title": "",
                "dataset_4_title": "",
                "dataset_5_title": "",
                "administering_ic": "",
                "advSearchFilters": [],
                "dataset_category": "",
                "research_program": "",
                "research_question": "",
                "study_description": "",
                "clinical_trial_link": "",
                "dataset_description": "",
                "research_focus_area": "",
                "dataset_1_description": "",
                "dataset_2_description": "",
                "dataset_3_description": "",
                "dataset_4_description": "",
                "dataset_5_description": "",
                "data_availability": "available",
            },
        },
        "UBC02": {
            "_guid_type": "discovery_metadata",
            "gen3_discovery": {
                "tags": [],
                "authz": "/programs/open",
                "sites": "",
                "summary": "",
                "study_description_summary": "",
                "study_url": "",
                "location": "",
                "subjects": 60,
                "__manifest": "",
                "study_name": "",
                "study_name_title": "",
                "study_type": "",
                "institutions": "",
                "year_awarded": "",
                "investigators": "",
                "investigators_name": "",
                "project_title": "Basal and Luminal Molecular Subtypes in Naturally-Occurring Canine Urothelial Carcinoma Are Associated With Tumor Immune Signatures and Dog Breed",
                "protocol_name": "",
                "study_summary": "",
                "_file_manifest": "",
                "dataset_1_type": "",
                "dataset_2_type": "",
                "dataset_3_type": "",
                "dataset_4_type": "",
                "dataset_5_type": "",
                "project_number": "UBC02",
                "dataset_1_title": "",
                "dataset_2_title": "",
                "dataset_3_title": "",
                "dataset_4_title": "",
                "dataset_5_title": "",
                "administering_ic": "",
                "advSearchFilters": [],
                "dataset_category": "",
                "research_program": "",
                "research_question": "",
                "study_description": "",
                "clinical_trial_link": "",
                "dataset_description": "",
                "research_focus_area": "",
                "dataset_1_description": "",
                "dataset_2_description": "",
                "dataset_3_description": "",
                "dataset_4_description": "",
                "dataset_5_description": "",
                "data_availability": "available",
            },
        },
    }
