"""metadata

Revision ID: 27d2876d014e
Revises: 4d93784a25e5
Create Date: 2022-07-01 12:02:13.122113

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.schema import Sequence, CreateSequence, DropSequence


# revision identifiers, used by Alembic.
revision = "27d2876d014e"
down_revision = "4d93784a25e5"
branch_labels = None
depends_on = None


def upgrade():
    op.execute(CreateSequence(Sequence("metadata_internal_id_seq")))
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "metadata_internal",
        sa.Column("metadata_guid", sa.Unicode(), nullable=True),
        sa.Column(
            "id",
            sa.BigInteger(),
            server_default=sa.text("nextval('metadata_internal_id_seq')"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["metadata_guid"], ["metadata.guid"], ondelete="CASCADE"
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("metadata_internal")
    # ### end Alembic commands ###
    op.execute(DropSequence(Sequence("metadata_internal_id_seq")))
