name: Build Image and Push to Registries

on: push

jobs:
  ci:
    name: Build Image and Push to Registries
    # test branch
    uses: uc-cdis/.github/.github/workflows/image_build_push.yaml@test/pin_runner_os_version
    secrets:
      ECR_AWS_ACCESS_KEY_ID: ${{ secrets.ECR_AWS_ACCESS_KEY_ID }}
      ECR_AWS_SECRET_ACCESS_KEY: ${{ secrets.ECR_AWS_SECRET_ACCESS_KEY }}
      QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      QUAY_ROBOT_TOKEN: ${{ secrets.QUAY_ROBOT_TOKEN }}
