name: Integration Tests

on: pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  integration_tests:
    name: Integration tests
    uses: uc-cdis/.github/.github/workflows/integration_tests.yaml@chore/update_integration_test_workflow
    with:
      SERVICE_TO_TEST: mds
    secrets:
      CI_AWS_ACCESS_KEY_ID: ${{ secrets.CI_AWS_ACCESS_KEY_ID }}
      CI_AWS_SECRET_ACCESS_KEY: ${{ secrets.CI_AWS_SECRET_ACCESS_KEY }}
      JENKINS_API_TOKEN: ${{ secrets.JENKINS_API_TOKEN }}
      QA_DASHBOARD_S3_PATH: ${{ secrets.QA_DASHBOARD_S3_PATH }}
