name: Integration Tests

on: pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  integration_tests:
    name: Integration tests
    uses: uc-cdis/gen3-code-vigil/.github/workflows/shared_integration_tests.yaml@chore/single_service_test_run
    with:
      SERVICE_TO_TEST: mds
    secrets: inherit  #pragma: allowlist secret
