name: Integration Tests

on: pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  integration_tests:
    name: Integration tests
    uses: uc-cdis/.github/.github/workflows/integration_tests.yaml@chore/update_integration_test_workflow
    with:
      SERVICE_TO_TEST: mds
    secrets: inherit  #pragma: allowlist secret
